# Generated by Django 2.2.5 on 2020-05-14 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_menucategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='ctg_image',
            field=models.ImageField(blank=True, upload_to='ctg-images/'),
        ),
    ]
