# Generated by Django 2.2.5 on 2020-05-14 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_auto_20200514_1230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='ctg_image',
            field=models.ImageField(upload_to='ctg-images/'),
        ),
    ]
